### ISSUE TITLE
Leaked SDK ?!

### ISSUE THREAD

**Issue by atc1441** [lj19940623/Remote_shutter_yc1039_yichip#1]
Take a look at this :)

https://github.com/Beacool-Bt/classic_bt/tree/master/cm0

**Comment by lj19940623** [comment]
Not for yc10xx, I believe it is a leaked SDK for yc1121_fpga. https://github.com/Beacool-Bt/classic_bt/blob/master/cm0/doc/M0%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA%E6%B5%81%E7%A8%8B.pdf

**Comment by atc1441** [comment]
Ok but maybe it still helps with getting into it.

Better then nothing i hope

**Comment by lj19940623** [comment]
Thanks for your info. Closing issue
